// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtsJ2twHS5o6ysQuSPopj-GOWzb81Cyso',
    appId: '1:130262288639:web:de238d15c8ec3469cee4ca',
    messagingSenderId: '130262288639',
    projectId: 'tokogadget-8d641',
    authDomain: 'tokogadget-8d641.firebaseapp.com',
    storageBucket: 'tokogadget-8d641.firebasestorage.app',
    measurementId: 'G-EB4FQRDLW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YmY-xVlLTFMkTeflUrGthyWilTTE54w',
    appId: '1:130262288639:android:0385777d1e3abb1ecee4ca',
    messagingSenderId: '130262288639',
    projectId: 'tokogadget-8d641',
    storageBucket: 'tokogadget-8d641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfBDsgGon-qJRluhhnGezjcAJUb3luY8w',
    appId: '1:130262288639:ios:937b4f51541d776fcee4ca',
    messagingSenderId: '130262288639',
    projectId: 'tokogadget-8d641',
    storageBucket: 'tokogadget-8d641.firebasestorage.app',
    iosBundleId: 'com.example.tokoGadget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfBDsgGon-qJRluhhnGezjcAJUb3luY8w',
    appId: '1:130262288639:ios:937b4f51541d776fcee4ca',
    messagingSenderId: '130262288639',
    projectId: 'tokogadget-8d641',
    storageBucket: 'tokogadget-8d641.firebasestorage.app',
    iosBundleId: 'com.example.tokoGadget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtsJ2twHS5o6ysQuSPopj-GOWzb81Cyso',
    appId: '1:130262288639:web:0869836369c956b4cee4ca',
    messagingSenderId: '130262288639',
    projectId: 'tokogadget-8d641',
    authDomain: 'tokogadget-8d641.firebaseapp.com',
    storageBucket: 'tokogadget-8d641.firebasestorage.app',
    measurementId: 'G-QQZ7HNCZKK',
  );
}
